// <auto-generated />
using System;
using IP.AccIPInfo.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IP.AccIPInfo.Persistence.Migrations
{
    [DbContext(typeof(AccIPDbContext))]
    [Migration("20260304034744_V1")]
    partial class V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("IP.AccIPInfo.Domain.AccountMovements.AccountMovementSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccountIPId")
                        .HasColumnType("char(36)");

                    b.Property<int>("AccountNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("CancelAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("CancelQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("MovementDateHour")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ReturnAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("ReturnAmountParcial")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("ReturnQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ReturnQuantityParcial")
                        .HasColumnType("int");

                    b.Property<decimal>("SettledAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("SettledQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountIPId");

                    b.ToTable("AccountsIPMovementsSummary", "AccIPInfo");
                });

            modelBuilder.Entity("IP.AccIPInfo.Domain.AccountSubscriptions.AccountSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("AccountSubscriptions", (string)null);
                });

            modelBuilder.Entity("IP.AccIPInfo.Domain.AccountsIP.AccountIP", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("AccountsIP", (string)null);
                });

            modelBuilder.Entity("IP.AccIPInfo.Domain.IntegratorSystems.IntegratorSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SiteUrl")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("IntegratorSystems", (string)null);
                });

            modelBuilder.Entity("IP.Shared.Domain.Entities.AuditTrail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AffectedColumns")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NewValues")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("longtext");

                    b.Property<string>("OldValues")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("longtext");

                    b.Property<string>("PrimaryKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.ToTable("AuditTrails", (string)null);
                });

            modelBuilder.Entity("IP.AccIPInfo.Domain.AccountMovements.AccountMovementSummary", b =>
                {
                    b.HasOne("IP.AccIPInfo.Domain.AccountsIP.AccountIP", "AccountIP")
                        .WithMany()
                        .HasForeignKey("AccountIPId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("IP.Shared.Domain.Entities.EntityAuditableInfo", "AuditableInfo", b1 =>
                        {
                            b1.Property<Guid>("AccountMovementSummaryId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime(6)");

                            b1.Property<string>("UpdatedBy")
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<DateTime?>("UpdatedDate")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("AccountMovementSummaryId");

                            b1.ToTable("AccountsIPMovementsSummary", "AccIPInfo");

                            b1.WithOwner()
                                .HasForeignKey("AccountMovementSummaryId");
                        });

                    b.Navigation("AccountIP");

                    b.Navigation("AuditableInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("IP.AccIPInfo.Domain.AccountSubscriptions.AccountSubscription", b =>
                {
                    b.OwnsOne("IP.Shared.Domain.Entities.EntityActivableInfo", "ActivableInfo", b1 =>
                        {
                            b1.Property<Guid>("AccountSubscriptionId")
                                .HasColumnType("char(36)");

                            b1.Property<bool>("Active")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint(1)")
                                .HasDefaultValue(true);

                            b1.Property<string>("InativeReason")
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("text(5000)");

                            b1.HasKey("AccountSubscriptionId");

                            b1.ToTable("AccountSubscriptions");

                            b1.WithOwner()
                                .HasForeignKey("AccountSubscriptionId");
                        });

                    b.OwnsOne("IP.Shared.Domain.Entities.EntityAuditableInfo", "AuditableInfo", b1 =>
                        {
                            b1.Property<Guid>("AccountSubscriptionId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime(6)");

                            b1.Property<string>("UpdatedBy")
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<DateTime?>("UpdatedDate")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("AccountSubscriptionId");

                            b1.ToTable("AccountSubscriptions");

                            b1.WithOwner()
                                .HasForeignKey("AccountSubscriptionId");
                        });

                    b.OwnsOne("IP.Shared.Domain.Entities.EntityDeletableInfo", "DeletableInfo", b1 =>
                        {
                            b1.Property<Guid>("AccountSubscriptionId")
                                .HasColumnType("char(36)");

                            b1.Property<bool>("Deleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint(1)")
                                .HasDefaultValue(false);

                            b1.Property<string>("DeletedReason")
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("text(5000)");

                            b1.HasKey("AccountSubscriptionId");

                            b1.ToTable("AccountSubscriptions");

                            b1.WithOwner()
                                .HasForeignKey("AccountSubscriptionId");
                        });

                    b.OwnsOne("IP.AccIPInfo.Domain.AccountSubscriptions.AccountSubscriptionNameValue", "Name", b1 =>
                        {
                            b1.Property<Guid>("AccountSubscriptionId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(true)
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("ValueNormalized")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(true)
                                .HasColumnType("varchar(50)");

                            b1.HasKey("AccountSubscriptionId");

                            b1.ToTable("AccountSubscriptions");

                            b1.WithOwner()
                                .HasForeignKey("AccountSubscriptionId");
                        });

                    b.Navigation("ActivableInfo")
                        .IsRequired();

                    b.Navigation("AuditableInfo")
                        .IsRequired();

                    b.Navigation("DeletableInfo")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("IP.AccIPInfo.Domain.AccountsIP.AccountIP", b =>
                {
                    b.OwnsOne("IP.Shared.Domain.Entities.EntityAuditableInfo", "AuditableInfo", b1 =>
                        {
                            b1.Property<Guid>("AccountIPId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime(6)");

                            b1.Property<string>("UpdatedBy")
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<DateTime?>("UpdatedDate")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("AccountIPId");

                            b1.ToTable("AccountsIP");

                            b1.WithOwner()
                                .HasForeignKey("AccountIPId");
                        });

                    b.OwnsOne("IP.Shared.Domain.Entities.EntityDeletableInfo", "DeletableInfo", b1 =>
                        {
                            b1.Property<Guid>("AccountIPId")
                                .HasColumnType("char(36)");

                            b1.Property<bool>("Deleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint(1)")
                                .HasDefaultValue(false);

                            b1.Property<string>("DeletedReason")
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("text(5000)");

                            b1.HasKey("AccountIPId");

                            b1.ToTable("AccountsIP");

                            b1.WithOwner()
                                .HasForeignKey("AccountIPId");
                        });

                    b.OwnsOne("IP.AccIPInfo.Domain.AccountsIP.AccountIPAccountSubscription", "Subscription", b1 =>
                        {
                            b1.Property<Guid>("AccountIPId")
                                .HasColumnType("char(36)");

                            b1.Property<Guid?>("Id")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Name")
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<string>("NameNormalized")
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.HasKey("AccountIPId");

                            b1.ToTable("AccountsIP");

                            b1.WithOwner()
                                .HasForeignKey("AccountIPId");
                        });

                    b.OwnsOne("IP.AccIPInfo.Domain.AccountsIP.AccountIPAlias", "Alias", b1 =>
                        {
                            b1.Property<Guid>("AccountIPId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<string>("ValueNormalized")
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.HasKey("AccountIPId");

                            b1.ToTable("AccountsIP");

                            b1.WithOwner()
                                .HasForeignKey("AccountIPId");
                        });

                    b.OwnsOne("IP.AccIPInfo.Domain.AccountsIP.AccountIPBusinessBranchSegment", "BusinessBranchSegment", b1 =>
                        {
                            b1.Property<Guid>("AccountIPId")
                                .HasColumnType("char(36)");

                            b1.Property<Guid?>("BranchId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("BranchName")
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<Guid?>("SegmentId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("SegmentName")
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.HasKey("AccountIPId");

                            b1.ToTable("AccountsIP");

                            b1.WithOwner()
                                .HasForeignKey("AccountIPId");
                        });

                    b.OwnsOne("IP.AccIPInfo.Domain.AccountsIP.AccountIPCustomer", "Customer", b1 =>
                        {
                            b1.Property<Guid>("AccountIPId")
                                .HasColumnType("char(36)");

                            b1.Property<Guid?>("Id")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<string>("NameNormalized")
                                .IsRequired()
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.HasKey("AccountIPId");

                            b1.ToTable("AccountsIP");

                            b1.WithOwner()
                                .HasForeignKey("AccountIPId");
                        });

                    b.OwnsOne("IP.AccIPInfo.Domain.AccountsIP.AccountIPIntegratorSistem", "Integrator", b1 =>
                        {
                            b1.Property<Guid>("AccountIPId")
                                .HasColumnType("char(36)");

                            b1.Property<Guid?>("Id")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Name")
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<string>("NameNormalized")
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.HasKey("AccountIPId");

                            b1.ToTable("AccountsIP");

                            b1.WithOwner()
                                .HasForeignKey("AccountIPId");
                        });

                    b.OwnsOne("IP.AccIPInfo.Domain.AccountsIP.AccountIPOwner", "Owner", b1 =>
                        {
                            b1.Property<Guid>("AccountIPId")
                                .HasColumnType("char(36)");

                            b1.Property<Guid?>("Id")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Name")
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<string>("NameNormalized")
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<bool?>("OwnerIsIP")
                                .HasColumnType("tinyint(1)");

                            b1.HasKey("AccountIPId");

                            b1.ToTable("AccountsIP");

                            b1.WithOwner()
                                .HasForeignKey("AccountIPId");
                        });

                    b.OwnsOne("IP.AccIPInfo.Domain.AccountsIP.AccountIPRetailer", "Retailer", b1 =>
                        {
                            b1.Property<Guid>("AccountIPId")
                                .HasColumnType("char(36)");

                            b1.Property<Guid?>("Id")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Name")
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<string>("NameNormalized")
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.HasKey("AccountIPId");

                            b1.ToTable("AccountsIP");

                            b1.WithOwner()
                                .HasForeignKey("AccountIPId");
                        });

                    b.Navigation("Alias");

                    b.Navigation("AuditableInfo")
                        .IsRequired();

                    b.Navigation("BusinessBranchSegment");

                    b.Navigation("Customer")
                        .IsRequired();

                    b.Navigation("DeletableInfo")
                        .IsRequired();

                    b.Navigation("Integrator");

                    b.Navigation("Owner");

                    b.Navigation("Retailer");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("IP.AccIPInfo.Domain.IntegratorSystems.IntegratorSystem", b =>
                {
                    b.OwnsOne("IP.Shared.Domain.Entities.EntityActivableInfo", "ActivableInfo", b1 =>
                        {
                            b1.Property<Guid>("IntegratorSystemId")
                                .HasColumnType("char(36)");

                            b1.Property<bool>("Active")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint(1)")
                                .HasDefaultValue(true);

                            b1.Property<string>("InativeReason")
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("text(5000)");

                            b1.HasKey("IntegratorSystemId");

                            b1.ToTable("IntegratorSystems");

                            b1.WithOwner()
                                .HasForeignKey("IntegratorSystemId");
                        });

                    b.OwnsOne("IP.Shared.Domain.Entities.EntityAuditableInfo", "AuditableInfo", b1 =>
                        {
                            b1.Property<Guid>("IntegratorSystemId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime(6)");

                            b1.Property<string>("UpdatedBy")
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<DateTime?>("UpdatedDate")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("IntegratorSystemId");

                            b1.ToTable("IntegratorSystems");

                            b1.WithOwner()
                                .HasForeignKey("IntegratorSystemId");
                        });

                    b.OwnsOne("IP.Shared.Domain.Entities.EntityDeletableInfo", "DeletableInfo", b1 =>
                        {
                            b1.Property<Guid>("IntegratorSystemId")
                                .HasColumnType("char(36)");

                            b1.Property<bool>("Deleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint(1)")
                                .HasDefaultValue(false);

                            b1.Property<string>("DeletedReason")
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("text(5000)");

                            b1.HasKey("IntegratorSystemId");

                            b1.ToTable("IntegratorSystems");

                            b1.WithOwner()
                                .HasForeignKey("IntegratorSystemId");
                        });

                    b.OwnsOne("IP.AccIPInfo.Domain.IntegratorSystems.IntegratorSystemNameValue", "Name", b1 =>
                        {
                            b1.Property<Guid>("IntegratorSystemId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(true)
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("ValueNormalized")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(true)
                                .HasColumnType("varchar(50)");

                            b1.HasKey("IntegratorSystemId");

                            b1.ToTable("IntegratorSystems");

                            b1.WithOwner()
                                .HasForeignKey("IntegratorSystemId");
                        });

                    b.Navigation("ActivableInfo")
                        .IsRequired();

                    b.Navigation("AuditableInfo")
                        .IsRequired();

                    b.Navigation("DeletableInfo")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
