// <auto-generated />
using System;
using IP.Com.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IP.Com.Persistence.Migrations
{
    [DbContext(typeof(ComDbContext))]
    [Migration("20260304034626_V1")]
    partial class V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("IP.Com.Domain.EmailsSchedule.EmailSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("longtext");

                    b.Property<string>("CarbonCopy")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("longtext");

                    b.Property<string>("Copy")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("longtext");

                    b.Property<string>("ErrorMessages")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastAttemptDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("longtext");

                    b.Property<bool>("Sended")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("longtext");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.ToTable("EmailsSchedule", (string)null);
                });

            modelBuilder.Entity("IP.Shared.Domain.Entities.AuditTrail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AffectedColumns")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NewValues")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("longtext");

                    b.Property<string>("OldValues")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("longtext");

                    b.Property<string>("PrimaryKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.ToTable("AuditTrails", (string)null);
                });

            modelBuilder.Entity("IP.Com.Domain.EmailsSchedule.EmailSchedule", b =>
                {
                    b.OwnsOne("IP.Shared.Domain.Entities.EntityAuditableInfo", "AuditableInfo", b1 =>
                        {
                            b1.Property<Guid>("EmailScheduleId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime(6)");

                            b1.Property<string>("UpdatedBy")
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<DateTime?>("UpdatedDate")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("EmailScheduleId");

                            b1.ToTable("EmailsSchedule");

                            b1.WithOwner()
                                .HasForeignKey("EmailScheduleId");
                        });

                    b.Navigation("AuditableInfo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
