// <auto-generated />
using System;
using IP.IDI.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IP.IDI.Persistence.Migrations
{
    [DbContext(typeof(IDIDbContext))]
    [Migration("20260304034423_V1")]
    partial class V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("IP.IDI.Domain.AppGuides.AppGuide", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("LinkId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AppGuides", (string)null);
                });

            modelBuilder.Entity("IP.IDI.Domain.AppGuides.AppGuideViewed", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AppGuideId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AppGuideId");

                    b.HasIndex("UserId");

                    b.ToTable("AppGuideViewed", (string)null);
                });

            modelBuilder.Entity("IP.IDI.Domain.Roles.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("IP.IDI.Domain.Roles.AppRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("IP.IDI.Domain.Users.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail");

                    b.HasIndex("NormalizedUserName");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("IP.IDI.Domain.Users.AppUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("IP.IDI.Domain.Users.AppUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("IP.IDI.Domain.Users.AppUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("IP.IDI.Domain.Users.AppUserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Value")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("IP.Shared.Domain.Entities.AuditTrail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AffectedColumns")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NewValues")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("longtext");

                    b.Property<string>("OldValues")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("longtext");

                    b.Property<string>("PrimaryKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.ToTable("AuditTrails", (string)null);
                });

            modelBuilder.Entity("IP.IDI.Domain.AppGuides.AppGuide", b =>
                {
                    b.OwnsOne("IP.Shared.Domain.Entities.EntityActivableInfo", "ActivableInfo", b1 =>
                        {
                            b1.Property<Guid>("AppGuideId")
                                .HasColumnType("char(36)");

                            b1.Property<bool>("Active")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint(1)")
                                .HasDefaultValue(true);

                            b1.Property<string>("InativeReason")
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("text(5000)");

                            b1.HasKey("AppGuideId");

                            b1.ToTable("AppGuides");

                            b1.WithOwner()
                                .HasForeignKey("AppGuideId");
                        });

                    b.OwnsOne("IP.Shared.Domain.Entities.EntityAuditableInfo", "AuditableInfo", b1 =>
                        {
                            b1.Property<Guid>("AppGuideId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime(6)");

                            b1.Property<string>("UpdatedBy")
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<DateTime?>("UpdatedDate")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("AppGuideId");

                            b1.ToTable("AppGuides");

                            b1.WithOwner()
                                .HasForeignKey("AppGuideId");
                        });

                    b.OwnsOne("IP.Shared.Domain.Entities.EntityDeletableInfo", "DeletableInfo", b1 =>
                        {
                            b1.Property<Guid>("AppGuideId")
                                .HasColumnType("char(36)");

                            b1.Property<bool>("Deleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint(1)")
                                .HasDefaultValue(false);

                            b1.Property<string>("DeletedReason")
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("text(5000)");

                            b1.HasKey("AppGuideId");

                            b1.ToTable("AppGuides");

                            b1.WithOwner()
                                .HasForeignKey("AppGuideId");
                        });

                    b.Navigation("ActivableInfo")
                        .IsRequired();

                    b.Navigation("AuditableInfo")
                        .IsRequired();

                    b.Navigation("DeletableInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("IP.IDI.Domain.AppGuides.AppGuideViewed", b =>
                {
                    b.HasOne("IP.IDI.Domain.AppGuides.AppGuide", "AppGuide")
                        .WithMany("Users")
                        .HasForeignKey("AppGuideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IP.IDI.Domain.Users.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("IP.Shared.Domain.Entities.EntityActivableInfo", "ActivableInfo", b1 =>
                        {
                            b1.Property<Guid>("AppGuideViewedId")
                                .HasColumnType("char(36)");

                            b1.Property<bool>("Active")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint(1)")
                                .HasDefaultValue(true);

                            b1.Property<string>("InativeReason")
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("text(5000)");

                            b1.HasKey("AppGuideViewedId");

                            b1.ToTable("AppGuideViewed");

                            b1.WithOwner()
                                .HasForeignKey("AppGuideViewedId");
                        });

                    b.OwnsOne("IP.Shared.Domain.Entities.EntityAuditableInfo", "AuditableInfo", b1 =>
                        {
                            b1.Property<Guid>("AppGuideViewedId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime(6)");

                            b1.Property<string>("UpdatedBy")
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<DateTime?>("UpdatedDate")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("AppGuideViewedId");

                            b1.ToTable("AppGuideViewed");

                            b1.WithOwner()
                                .HasForeignKey("AppGuideViewedId");
                        });

                    b.Navigation("ActivableInfo")
                        .IsRequired();

                    b.Navigation("AppGuide");

                    b.Navigation("AuditableInfo")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IP.IDI.Domain.Roles.AppRole", b =>
                {
                    b.OwnsOne("IP.Shared.Domain.Entities.EntityActivableInfo", "ActivableInfo", b1 =>
                        {
                            b1.Property<Guid>("AppRoleId")
                                .HasColumnType("char(36)");

                            b1.Property<bool>("Active")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint(1)")
                                .HasDefaultValue(true);

                            b1.Property<string>("InativeReason")
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("text(5000)");

                            b1.HasKey("AppRoleId");

                            b1.ToTable("Roles");

                            b1.WithOwner()
                                .HasForeignKey("AppRoleId");
                        });

                    b.OwnsOne("IP.Shared.Domain.Entities.EntityAuditableInfo", "AuditableInfo", b1 =>
                        {
                            b1.Property<Guid>("AppRoleId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime(6)");

                            b1.Property<string>("UpdatedBy")
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<DateTime?>("UpdatedDate")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("AppRoleId");

                            b1.ToTable("Roles");

                            b1.WithOwner()
                                .HasForeignKey("AppRoleId");
                        });

                    b.OwnsOne("IP.Shared.Domain.Entities.EntityDeletableInfo", "DeletableInfo", b1 =>
                        {
                            b1.Property<Guid>("AppRoleId")
                                .HasColumnType("char(36)");

                            b1.Property<bool>("Deleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint(1)")
                                .HasDefaultValue(false);

                            b1.Property<string>("DeletedReason")
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("text(5000)");

                            b1.HasKey("AppRoleId");

                            b1.ToTable("Roles");

                            b1.WithOwner()
                                .HasForeignKey("AppRoleId");
                        });

                    b.Navigation("ActivableInfo")
                        .IsRequired();

                    b.Navigation("AuditableInfo")
                        .IsRequired();

                    b.Navigation("DeletableInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("IP.IDI.Domain.Roles.AppRoleClaim", b =>
                {
                    b.HasOne("IP.IDI.Domain.Roles.AppRole", "Role")
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("IP.IDI.Domain.Users.AppUser", b =>
                {
                    b.OwnsOne("IP.Shared.Domain.Entities.EntityActivableInfo", "ActivableInfo", b1 =>
                        {
                            b1.Property<Guid>("AppUserId")
                                .HasColumnType("char(36)");

                            b1.Property<bool>("Active")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint(1)")
                                .HasDefaultValue(true);

                            b1.Property<string>("InativeReason")
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("text(5000)");

                            b1.HasKey("AppUserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("AppUserId");
                        });

                    b.OwnsOne("IP.Shared.Domain.Entities.EntityAuditableInfo", "AuditableInfo", b1 =>
                        {
                            b1.Property<Guid>("AppUserId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime(6)");

                            b1.Property<string>("UpdatedBy")
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<DateTime?>("UpdatedDate")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("AppUserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("AppUserId");
                        });

                    b.OwnsOne("IP.Shared.Domain.Entities.EntityDeletableInfo", "DeletableInfo", b1 =>
                        {
                            b1.Property<Guid>("AppUserId")
                                .HasColumnType("char(36)");

                            b1.Property<bool>("Deleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint(1)")
                                .HasDefaultValue(false);

                            b1.Property<string>("DeletedReason")
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("text(5000)");

                            b1.HasKey("AppUserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("AppUserId");
                        });

                    b.Navigation("ActivableInfo")
                        .IsRequired();

                    b.Navigation("AuditableInfo")
                        .IsRequired();

                    b.Navigation("DeletableInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("IP.IDI.Domain.Users.AppUserClaim", b =>
                {
                    b.HasOne("IP.IDI.Domain.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IP.IDI.Domain.Users.AppUserLogin", b =>
                {
                    b.HasOne("IP.IDI.Domain.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IP.IDI.Domain.Users.AppUserRole", b =>
                {
                    b.HasOne("IP.IDI.Domain.Roles.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IP.IDI.Domain.Users.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IP.IDI.Domain.Users.AppUserToken", b =>
                {
                    b.HasOne("IP.IDI.Domain.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IP.IDI.Domain.AppGuides.AppGuide", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("IP.IDI.Domain.Roles.AppRole", b =>
                {
                    b.Navigation("RoleClaims");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("IP.IDI.Domain.Users.AppUser", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
