// <auto-generated />
using System;
using IP.Core.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IP.Core.Persistence.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    partial class CoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("IP.Core.Domain.Addresses.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(true)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("IP.Core.Domain.BusinessBranches.BusinessBranch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("BusinessBranches", (string)null);
                });

            modelBuilder.Entity("IP.Core.Domain.BusinessSegments.BusinessSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BusinessBranchId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessBranchId");

                    b.ToTable("BusinessSegments", (string)null);
                });

            modelBuilder.Entity("IP.Core.Domain.Cities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("IBGECode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .IsUnicode(true)
                        .HasColumnType("varchar(7)");

                    b.Property<Guid>("StateId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("IP.Core.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PersonTypeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("text(5000)");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("IP.Core.Domain.Employees.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("IP.Core.Domain.States.State", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(true)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("IBGECode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(true)
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.ToTable("States", (string)null);
                });

            modelBuilder.Entity("IP.Shared.Domain.Entities.AuditTrail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AffectedColumns")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NewValues")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("longtext");

                    b.Property<string>("OldValues")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("longtext");

                    b.Property<string>("PrimaryKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.ToTable("AuditTrails", (string)null);
                });

            modelBuilder.Entity("IP.Core.Domain.Addresses.Address", b =>
                {
                    b.HasOne("IP.Core.Domain.Cities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("IP.Shared.Domain.Entities.EntityActivableInfo", "ActivableInfo", b1 =>
                        {
                            b1.Property<Guid>("AddressId")
                                .HasColumnType("char(36)");

                            b1.Property<bool>("Active")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint(1)")
                                .HasDefaultValue(true);

                            b1.Property<string>("InativeReason")
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("text(5000)");

                            b1.HasKey("AddressId");

                            b1.ToTable("Addresses");

                            b1.WithOwner()
                                .HasForeignKey("AddressId");
                        });

                    b.OwnsOne("IP.Shared.Domain.Entities.EntityAuditableInfo", "AuditableInfo", b1 =>
                        {
                            b1.Property<Guid>("AddressId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime(6)");

                            b1.Property<string>("UpdatedBy")
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<DateTime?>("UpdatedDate")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("AddressId");

                            b1.ToTable("Addresses");

                            b1.WithOwner()
                                .HasForeignKey("AddressId");
                        });

                    b.OwnsOne("IP.Core.Domain.Addresses.NameAddressValue", "Name", b1 =>
                        {
                            b1.Property<Guid>("AddressId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("varchar(100)");

                            b1.Property<string>("ValueNormalized")
                                .IsRequired()
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("varchar(100)");

                            b1.HasKey("AddressId");

                            b1.ToTable("Addresses");

                            b1.WithOwner()
                                .HasForeignKey("AddressId");
                        });

                    b.OwnsOne("IP.Core.Domain.Addresses.NeighborhoodValue", "Neighborhood", b1 =>
                        {
                            b1.Property<Guid>("AddressId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("varchar(100)");

                            b1.Property<string>("ValueNormalized")
                                .IsRequired()
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("varchar(100)");

                            b1.HasKey("AddressId");

                            b1.ToTable("Addresses");

                            b1.WithOwner()
                                .HasForeignKey("AddressId");
                        });

                    b.Navigation("ActivableInfo")
                        .IsRequired();

                    b.Navigation("AuditableInfo")
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Neighborhood")
                        .IsRequired();
                });

            modelBuilder.Entity("IP.Core.Domain.BusinessBranches.BusinessBranch", b =>
                {
                    b.OwnsOne("IP.Shared.Domain.Entities.EntityActivableInfo", "ActivableInfo", b1 =>
                        {
                            b1.Property<Guid>("BusinessBranchId")
                                .HasColumnType("char(36)");

                            b1.Property<bool>("Active")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint(1)")
                                .HasDefaultValue(true);

                            b1.Property<string>("InativeReason")
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("text(5000)");

                            b1.HasKey("BusinessBranchId");

                            b1.ToTable("BusinessBranches");

                            b1.WithOwner()
                                .HasForeignKey("BusinessBranchId");
                        });

                    b.OwnsOne("IP.Shared.Domain.Entities.EntityAuditableInfo", "AuditableInfo", b1 =>
                        {
                            b1.Property<Guid>("BusinessBranchId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime(6)");

                            b1.Property<string>("UpdatedBy")
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<DateTime?>("UpdatedDate")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("BusinessBranchId");

                            b1.ToTable("BusinessBranches");

                            b1.WithOwner()
                                .HasForeignKey("BusinessBranchId");
                        });

                    b.OwnsOne("IP.Shared.Domain.Entities.EntityDeletableInfo", "DeletableInfo", b1 =>
                        {
                            b1.Property<Guid>("BusinessBranchId")
                                .HasColumnType("char(36)");

                            b1.Property<bool>("Deleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint(1)")
                                .HasDefaultValue(false);

                            b1.Property<string>("DeletedReason")
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("text(5000)");

                            b1.HasKey("BusinessBranchId");

                            b1.ToTable("BusinessBranches");

                            b1.WithOwner()
                                .HasForeignKey("BusinessBranchId");
                        });

                    b.OwnsOne("IP.Core.Domain.BusinessBranches.BusinessBranchNameValue", "Name", b1 =>
                        {
                            b1.Property<Guid>("BusinessBranchId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("varchar(100)");

                            b1.Property<string>("ValueNormalized")
                                .IsRequired()
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("varchar(100)");

                            b1.HasKey("BusinessBranchId");

                            b1.ToTable("BusinessBranches");

                            b1.WithOwner()
                                .HasForeignKey("BusinessBranchId");
                        });

                    b.Navigation("ActivableInfo")
                        .IsRequired();

                    b.Navigation("AuditableInfo")
                        .IsRequired();

                    b.Navigation("DeletableInfo")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("IP.Core.Domain.BusinessSegments.BusinessSegment", b =>
                {
                    b.HasOne("IP.Core.Domain.BusinessBranches.BusinessBranch", "BusinessBranch")
                        .WithMany("Segments")
                        .HasForeignKey("BusinessBranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("IP.Shared.Domain.Entities.EntityActivableInfo", "ActivableInfo", b1 =>
                        {
                            b1.Property<Guid>("BusinessSegmentId")
                                .HasColumnType("char(36)");

                            b1.Property<bool>("Active")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint(1)")
                                .HasDefaultValue(true);

                            b1.Property<string>("InativeReason")
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("text(5000)");

                            b1.HasKey("BusinessSegmentId");

                            b1.ToTable("BusinessSegments");

                            b1.WithOwner()
                                .HasForeignKey("BusinessSegmentId");
                        });

                    b.OwnsOne("IP.Shared.Domain.Entities.EntityAuditableInfo", "AuditableInfo", b1 =>
                        {
                            b1.Property<Guid>("BusinessSegmentId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime(6)");

                            b1.Property<string>("UpdatedBy")
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<DateTime?>("UpdatedDate")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("BusinessSegmentId");

                            b1.ToTable("BusinessSegments");

                            b1.WithOwner()
                                .HasForeignKey("BusinessSegmentId");
                        });

                    b.OwnsOne("IP.Shared.Domain.Entities.EntityDeletableInfo", "DeletableInfo", b1 =>
                        {
                            b1.Property<Guid>("BusinessSegmentId")
                                .HasColumnType("char(36)");

                            b1.Property<bool>("Deleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint(1)")
                                .HasDefaultValue(false);

                            b1.Property<string>("DeletedReason")
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("text(5000)");

                            b1.HasKey("BusinessSegmentId");

                            b1.ToTable("BusinessSegments");

                            b1.WithOwner()
                                .HasForeignKey("BusinessSegmentId");
                        });

                    b.OwnsOne("IP.Core.Domain.BusinessSegments.SegmentNameValue", "SegmentName", b1 =>
                        {
                            b1.Property<Guid>("BusinessSegmentId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("varchar(100)");

                            b1.Property<string>("ValueNormalized")
                                .IsRequired()
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("varchar(100)");

                            b1.HasKey("BusinessSegmentId");

                            b1.ToTable("BusinessSegments");

                            b1.WithOwner()
                                .HasForeignKey("BusinessSegmentId");
                        });

                    b.Navigation("ActivableInfo")
                        .IsRequired();

                    b.Navigation("AuditableInfo")
                        .IsRequired();

                    b.Navigation("BusinessBranch");

                    b.Navigation("DeletableInfo")
                        .IsRequired();

                    b.Navigation("SegmentName")
                        .IsRequired();
                });

            modelBuilder.Entity("IP.Core.Domain.Cities.City", b =>
                {
                    b.HasOne("IP.Core.Domain.States.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("IP.Shared.Domain.Entities.EntityActivableInfo", "ActivableInfo", b1 =>
                        {
                            b1.Property<Guid>("CityId")
                                .HasColumnType("char(36)");

                            b1.Property<bool>("Active")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint(1)")
                                .HasDefaultValue(true);

                            b1.Property<string>("InativeReason")
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("text(5000)");

                            b1.HasKey("CityId");

                            b1.ToTable("Cities");

                            b1.WithOwner()
                                .HasForeignKey("CityId");
                        });

                    b.OwnsOne("IP.Shared.Domain.Entities.EntityAuditableInfo", "AuditableInfo", b1 =>
                        {
                            b1.Property<Guid>("CityId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime(6)");

                            b1.Property<string>("UpdatedBy")
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<DateTime?>("UpdatedDate")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("CityId");

                            b1.ToTable("Cities");

                            b1.WithOwner()
                                .HasForeignKey("CityId");
                        });

                    b.OwnsOne("IP.Shared.Domain.Entities.EntityDeletableInfo", "DeletableInfo", b1 =>
                        {
                            b1.Property<Guid>("CityId")
                                .HasColumnType("char(36)");

                            b1.Property<bool>("Deleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint(1)")
                                .HasDefaultValue(false);

                            b1.Property<string>("DeletedReason")
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("text(5000)");

                            b1.HasKey("CityId");

                            b1.ToTable("Cities");

                            b1.WithOwner()
                                .HasForeignKey("CityId");
                        });

                    b.OwnsOne("IP.Core.Domain.Cities.CityNameValue", "Name", b1 =>
                        {
                            b1.Property<Guid>("CityId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(true)
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("ValueNormalized")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(true)
                                .HasColumnType("varchar(50)");

                            b1.HasKey("CityId");

                            b1.ToTable("Cities");

                            b1.WithOwner()
                                .HasForeignKey("CityId");
                        });

                    b.Navigation("ActivableInfo")
                        .IsRequired();

                    b.Navigation("AuditableInfo")
                        .IsRequired();

                    b.Navigation("DeletableInfo")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("IP.Core.Domain.Customers.Customer", b =>
                {
                    b.OwnsOne("IP.Shared.Domain.Entities.EntityAuditableInfo", "AuditableInfo", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime(6)");

                            b1.Property<string>("UpdatedBy")
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<DateTime?>("UpdatedDate")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("IP.Shared.Domain.Entities.EntityDeletableInfo", "DeletableInfo", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("char(36)");

                            b1.Property<bool>("Deleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint(1)")
                                .HasDefaultValue(false);

                            b1.Property<string>("DeletedReason")
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("text(5000)");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("IP.Core.Domain.Customers.CustomerName", "Name", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<string>("ValueNormalized")
                                .IsRequired()
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("IP.Core.Domain.Customers.CustomerTradingName", "TradingName", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<string>("ValueNormalized")
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("IP.Core.Domain.VO.CPFOrCNPJ", "DocumentNumber", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(14)
                                .IsUnicode(true)
                                .HasColumnType("varchar(14)");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.Navigation("AuditableInfo")
                        .IsRequired();

                    b.Navigation("DeletableInfo")
                        .IsRequired();

                    b.Navigation("DocumentNumber")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("TradingName")
                        .IsRequired();
                });

            modelBuilder.Entity("IP.Core.Domain.Employees.Employee", b =>
                {
                    b.OwnsOne("IP.Core.Domain.Employees.EmployeName", "Name", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<string>("ValueNormalized")
                                .IsRequired()
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("IP.Shared.Domain.Entities.EntityActivableInfo", "ActivableInfo", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("char(36)");

                            b1.Property<bool>("Active")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint(1)")
                                .HasDefaultValue(true);

                            b1.Property<string>("InativeReason")
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("text(5000)");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("IP.Shared.Domain.Entities.EntityAuditableInfo", "AuditableInfo", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime(6)");

                            b1.Property<string>("UpdatedBy")
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<DateTime?>("UpdatedDate")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("IP.Shared.Domain.Entities.EntityDeletableInfo", "DeletableInfo", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("char(36)");

                            b1.Property<bool>("Deleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint(1)")
                                .HasDefaultValue(false);

                            b1.Property<string>("DeletedReason")
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("text(5000)");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("IP.Core.Domain.Employees.EmployeeManager", "Manager", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("char(36)");

                            b1.Property<Guid?>("Id")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Name")
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<string>("NameNormalized")
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("IP.Core.Domain.Employees.EmployeeUser", "User", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("char(36)");

                            b1.Property<Guid?>("Id")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Name")
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<string>("NameNormalized")
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("IP.Core.Domain.VO.CPF", "CPF", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(11)
                                .IsUnicode(true)
                                .HasColumnType("varchar(11)");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.Navigation("ActivableInfo")
                        .IsRequired();

                    b.Navigation("AuditableInfo")
                        .IsRequired();

                    b.Navigation("CPF")
                        .IsRequired();

                    b.Navigation("DeletableInfo")
                        .IsRequired();

                    b.Navigation("Manager")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("IP.Core.Domain.States.State", b =>
                {
                    b.OwnsOne("IP.Shared.Domain.Entities.EntityAuditableInfo", "AuditableInfo", b1 =>
                        {
                            b1.Property<Guid>("StateId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime(6)");

                            b1.Property<string>("UpdatedBy")
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("varchar(256)");

                            b1.Property<DateTime?>("UpdatedDate")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("StateId");

                            b1.ToTable("States");

                            b1.WithOwner()
                                .HasForeignKey("StateId");
                        });

                    b.OwnsOne("IP.Shared.Domain.Entities.EntityDeletableInfo", "DeletableInfo", b1 =>
                        {
                            b1.Property<Guid>("StateId")
                                .HasColumnType("char(36)");

                            b1.Property<bool>("Deleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint(1)")
                                .HasDefaultValue(false);

                            b1.Property<string>("DeletedReason")
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("text(5000)");

                            b1.HasKey("StateId");

                            b1.ToTable("States");

                            b1.WithOwner()
                                .HasForeignKey("StateId");
                        });

                    b.OwnsOne("IP.Core.Domain.States.StateNameValue", "Name", b1 =>
                        {
                            b1.Property<Guid>("StateId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(true)
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("ValueNormalized")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(true)
                                .HasColumnType("varchar(50)");

                            b1.HasKey("StateId");

                            b1.ToTable("States");

                            b1.WithOwner()
                                .HasForeignKey("StateId");
                        });

                    b.Navigation("AuditableInfo")
                        .IsRequired();

                    b.Navigation("DeletableInfo")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("IP.Core.Domain.BusinessBranches.BusinessBranch", b =>
                {
                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
